### PR TITLE
enh: add download for fs-32k mesh/gii files

### PR DESCRIPTION
**Pull request by mgxd**
includes:
- L/R.sphere.32k_fs_LR.surf.gii
- resample_fsaverage
   - fsaverage5 LR sphere + midthickness
   - fsaverage6 LR sphere + midthickness
   - fs_32k LR sphere + midthickness

### CODE REVIEW

**Comment by effigies** [comment]
Do they also have the inflated surfaces? Those would be useful for plotting, so while we're going through the trouble of adding this seems like a good time to include them.

**Comment by mgxd** [comment]
those are not included in http://brainvis.wustl.edu/workbench/standard_mesh_atlases.zip

we could use the [conte69 32k meshes](https://github.com/mgxd/brainplot/tree/master/brainplot/Conte69_Atlas) for plotting, seeing as that what we have done in the past

**Comment by effigies** [comment]
Sure. I could go either way on including them in the same archive or a separate one. Probably cleaner to do two, but if you're almost always going to want them together, might be slightly simpler to do one.

**Comment by oesteban** [comment]
I think having them split won't hurt and will make maintenance easier.

**Comment by oesteban** [comment]
Hey @mgxd, do you think it would be very cumbersome to normalize names in a BIDS-like fashion?

I have done this for two templates so far and they look like:

```
tpl-MNI152NLin2009cAsym
├── CHANGES
├── template_description.json
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_brainmask.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_class-CSF_probtissue.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_class-GM_probtissue.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_class-WM_probtissue.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_label-carpet_atlas.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_label-eyemask_roi.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_label-facemask_roi.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_label-headmask_roi.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_PD.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_T1w_brain.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_T1w.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-01_T2w.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_brainmask.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_class-CSF_probtissue.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_class-GM_probtissue.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_class-WM_probtissue.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_label-carpet_atlas.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_label-eyemask_roi.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_label-facemask_roi.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_label-headmask_roi.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_PD.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_T1w_brain.nii.gz
├── tpl-MNI152NLin2009cAsym_space-MNI_res-02_T1w.nii.gz
└── tpl-MNI152NLin2009cAsym_space-MNI_res-02_T2w.nii.gz
tpl-OASIS30ANTs
├── CHANGES
├── template_description.json
├── tpl-OASIS30ANTs_res-01_brainmask.nii.gz
├── tpl-OASIS30ANTs_res-01_class-brainmask_probtissue.nii.gz
├── tpl-OASIS30ANTs_res-01_class-bstem_probtissue.nii.gz
├── tpl-OASIS30ANTs_res-01_class-Cerebellum_probtissue.nii.gz
├── tpl-OASIS30ANTs_res-01_class-CGM_probtissue.nii.gz
├── tpl-OASIS30ANTs_res-01_class-CSF_probtissue.nii.gz
├── tpl-OASIS30ANTs_res-01_class-DGM_probtissue.nii.gz
├── tpl-OASIS30ANTs_res-01_class-WM_probtissue.nii.gz
├── tpl-OASIS30ANTs_res-01_label-BrainCerebellumExtraction_roi.nii.gz
├── tpl-OASIS30ANTs_res-01_label-BrainCerebellumRegistration_roi.nii.gz
├── tpl-OASIS30ANTs_res-01_T1w_brain.nii.gz
├── tpl-OASIS30ANTs_res-01_T1w.nii.gz
├── tpl-OASIS30ANTs_res-01_variant-4_dtissue.nii.gz
└── tpl-OASIS30ANTs_res-01_variant-6_dtissue.nii.gz
```

**Comment by mgxd** [comment]
this should be easy enough for the `conte69` template (tpl-Conte69), but the hcp32k upload contains 3 types of files (fsavg5, fsavg6, fs_LR) - how would you recommend formatting this?

**Comment by oesteban** [comment]
Using `variant-`. WDYT @chrisfilo?

**Comment by effigies** [comment]
What about `space`? We treat `fsaverage` and `fsaverage5` as spaces in fmriprep.

**Comment by chrisfilo** [comment]
`space` seems a better fit

**Comment by oesteban** [comment]
Actually: https://mail.nmr.mgh.harvard.edu/pipermail/freesurfer/2012-May/024088.html

**Comment by effigies** [comment]
We've been using space specifically to refer to the mesh in the case of surfaces, e.g., `fsnative`, `fsaverage`, etc.

Is there any advantage to specifying `MNI305` and then adding another indicator of the mesh?

**Comment by oesteban** [comment]
I think the explicit better than implicit applies here. Also, this particular use of space- is inconsistent with the use for volumes.

Finally (and we are considering stuff like this), let's imagine we have very precise transforms calculated between MNI152NlinAsym2009c-OASIS30ANTs-MNI305. It would be then fairly easy to move volume data and points between spaces. Having very present the space helps understand transforms quickly and preempts problems when writing workflows.

**Comment by effigies** [comment]
I think for so substantial a change to the draft spec, it might be good to open discussion either on the spec or in the mailing list.

**Comment by chrisfilo** [comment]
As I [mentioned on the mailing list](https://groups.google.com/d/msg/bids-discussion/GjK91pcyCyg/0aImWKwCAAAJ) the naming convention for storing templates in this particular repository might be outside of the scope of BIDS Derivatives. Thus it might be easier to agree on one convention for the purpose of workflows and stick to it.

**Comment by oesteban** [comment]
I agree with both: regarding niworkflows/fmriprep/etc we would move forward faster if we assume that this templates organization falls outside BIDS. However, I also agree with CM on that we should nonetheless bring this discussion to BIDS Derivatives (whether `fsaverage`, `fsaverage5` are legit spaces or we should use the appropriate -mni305- space key and encode sampling density with a different key).

So let's settle a directive for niworkflows and the templates repo independently of the future of BIDS Derivatives.

FMRIPREP should not update the outputs though, until some decision is made in BIDS Derivatives realm.

- So, still `space-` only or this would be something like `space-MNI305_variant-fsaverage`? I would vote for the latter.
- Does splitting (templates repo vs. BIDS) sound satisfactory for all?

**Comment by effigies** [comment]
Ah, I misunderstood the scope of what was being proposed. I thought we were suggesting changing how `space` worked for surfaces throughout the derivatives.

**Comment by effigies** [comment]
> So, still space- only or this would be something like space-MNI305_variant-fsaverage? I would vote for the latter.

I don't have a strong opinion, here. Especially if we're not going for standards compliant.

> Does splitting (templates repo vs. BIDS) sound satisfactory for all?

I don't understand this question.

**Comment by oesteban** [comment]
> I don't understand this question.

Whether not going for standards compliance in this context works for you.

**Comment by effigies** [comment]
Ah, yeah. That's fine. It sounds like from the linked discussion that there's no existing standard to apply, so any old thing is fine with me. It may be we'll want to change in the future, but that's true for any decision made here.

**Comment by effigies** [comment]
What's the status on this one? @mgxd is there a clear path ahead, or do we need to resolve anything?

**Comment by mgxd** [comment]
@effigies looks clear - just uploaded `tpl-hcpLR32k` with the following

```
CHANGES
template_description.json
tpl-hcpLR32k_space-fsaverage5_midthickness.L.shape.gii
tpl-hcpLR32k_space-fsaverage5_midthickness.R.shape.gii
tpl-hcpLR32k_space-fsaverage5_sphere.L.surf.gii
tpl-hcpLR32k_space-fsaverage5_sphere.R.surf.gii
tpl-hcpLR32k_space-fsaverage6_midthickness.L.shape.gii
tpl-hcpLR32k_space-fsaverage6_midthickness.R.shape.gii
tpl-hcpLR32k_space-fsaverage6_sphere.L.surf.gii
tpl-hcpLR32k_space-fsaverage6_sphere.R.surf.gii
tpl-hcpLR32k_space-fsLR_deformed.L.surf.gii
tpl-hcpLR32k_space-fsLR_deformed.R.surf.gii
tpl-hcpLR32k_space-fsLR_midthickness.L.shape.gii
tpl-hcpLR32k_space-fsLR_midthickness.R.shape.gii
tpl-hcpLR32k_space-fsLR_sphere.L.surf.gii
tpl-hcpLR32k_space-fsLR_sphere.R.surf.gii
```

does this look satisfactory?

**Comment by effigies** [comment]
Going by https://github.com/poldracklab/niworkflows/pull/243#issuecomment-393346878, I think you'll need to do `rename "s/space-/space-MNI305_variant-/" *.gii`. @oesteban was that what we agreed on?

**Comment by oesteban** [comment]
Yep, I would prefer to be a bit too orthodox here, and do @effigies' suggested rename.

**Comment by effigies** [comment]
Thanks @oesteban. @mgxd if you have a few minutes to polish this one off, today, I'd appreciate it. If you're not going to have time, let me know.

**Comment by mgxd** [comment]
ok, before I change any code, any final comments on the templates?

### tpl-conte69LR32k
CHANGES
template_description.json
tpl-conte69LR32k_space-MNI305_variant-inflated.L.surf.gii
tpl-conte69LR32k_space-MNI305_variant-inflated.R.surf.gii
tpl-conte69LR32k_space-MNI305_variant-midthickness.L.surf.gii
tpl-conte69LR32k_space-MNI305_variant-midthickness.R.surf.gii
tpl-conte69LR32k_space-MNI305_variant-vinflated.L.surf.gii
tpl-conte69LR32k_space-MNI305_variant-vinflated.R.surf.gii

### tpl-hcpLR32k
CHANGES
template_description.json
tpl-hcpLR32k_space-MNI305_variant-fsLR_deformed.L.surf.gii
tpl-hcpLR32k_space-MNI305_variant-fsLR_deformed.R.surf.gii
tpl-hcpLR32k_space-MNI305_variant-fsLR_midthickness.L.shape.gii
tpl-hcpLR32k_space-MNI305_variant-fsLR_midthickness.R.shape.gii
tpl-hcpLR32k_space-MNI305_variant-fsLR_sphere.L.surf.gii
tpl-hcpLR32k_space-MNI305_variant-fsLR_sphere.R.surf.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage5_midthickness.L.shape.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage5_midthickness.R.shape.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage5_sphere.L.surf.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage5_sphere.R.surf.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage6_midthickness.L.shape.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage6_midthickness.R.shape.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage6_sphere.L.surf.gii
tpl-hcpLR32k_space-MNI305_variant-fsaverage6_sphere.R.surf.gii

**Comment by effigies** [comment]
`tpl-conte69LR32k_space-MNI305_variant-inflated.L.surf.gii`

What's should be the variant here? `variant-conte69LR32k`? Is this comparable to `fsaverage5`?

**Comment by mgxd** [comment]
@effigies i've amended it to
```
tpl-conte69_space-MNI305_variant-fsLR32k_inflated.L.surf.gii
...
```
the template was acquired [here](http://brainvis.wustl.edu/wiki/index.php//Caret:Atlases/Conte69_Atlas), and these are 32k meshes. I'm happy with this structure, wdyt?

**Comment by effigies** [comment]
Sounds good.

**Comment by oesteban** [comment]
I'm cleaning up the tarfile and adding some fields to the `template_description.json`. Particularly, some hidden files made it into the package. I also wanted to add the link you shared above.

**Pull request merged**
