### PR TITLE
Resume external nipype dependency

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by effigies** [comment]
* [ ] poldracklab/fmriprep#1133
* [ ] poldracklab/mriqc#715

**Comment by effigies** [comment]
@oesteban I'd suggest merging and releasing 0.4.0 when MRIQC passes. This + ReportCapableInterfaces are a fairly significant change.

**Comment by effigies** [comment]
@oesteban Any opposition to an 0.4.0 release?

**Comment by oesteban** [comment]
No opposition at all!

**Pull request merged**
