### PR TITLE
[RTM] Added simple interface for visualising masks.

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by effigies** [comment]
Could smoke test this pretty quickly by hooking up its inputs to the outputs of [BETRPT](https://github.com/poldracklab/niworkflows/blob/master/niworkflows/tests/test_reports.py#L135-L145).

**Comment by chrisfilo** [comment]
https://79-75443898-gh.circle-artifacts.com/0/home/ubuntu/scratch/py3/testSimpleShowMaskRPT.html

**Comment by effigies** [comment]
Is that what that mask is supposed to look like?

**Comment by chrisfilo** [comment]
Yeah it's a broad mask used to speed up ANTs brain extraction.

**Pull request merged**
