### PR TITLE
ENH: Add helper function for cleaning a directory

### PR DESCRIPTION
**Pull request by mgxd**
instead of deleting and remaking (https://github.com/nipy/nipype/blob/792988f19c427c6f631df4d38a5942063f4b8d46/nipype/utils/filemanip.py#L768) (lol docstring), keep and clean directory

### CODE REVIEW

**Comment by effigies** [comment]
This is going to be subject to race conditions. Instead of returning `False`, you may want to `continue`, and at the end `return not list(os.scandir(path)).`

**Comment by mgxd** [comment]
sorry - i'm not seeing the race condition. can you explain?

**Comment by effigies** [comment]
Two threads or processes calling this function could race. `rmtree` and (I think) `unlink` will raise an error if the thing they're trying to remove doesn't exist.

**Comment by effigies** [comment]
Should we just ratchet to 3.6+ and stop worrying about `PathLike`?

**Comment by mgxd** [comment]
i think that finally did the trick (i can't wait til we drop 3.5)

re: the race condition - I think that may be beyond the intended use of this (planned to port over to fmriprep to make reruns easier). what about adding a line in the docstring explicitly warning this is not thread/multiprocess safe?

**Comment by effigies** [comment]
> what about adding a line in the docstring explicitly warning this is not thread/multiprocess safe?

Sure.

**Pull request merged**
