### PR TITLE
PIN: Update nipype

### PR DESCRIPTION
**Pull request by effigies**
Includes nipy/nipype#2198, nipy/nipype#2200, nipy/nipype#2205

Pending:

* [x] [FMRIPREP test](https://circleci.com/gh/effigies/fmriprep/861)
* [ ] [MRIQC test](https://circleci.com/gh/effigies/mriqc/16)

Edit: Added a further pin. If that causes issues, I'll drop it.

### CODE REVIEW

**Comment by effigies** [comment]
@oesteban Does we need to include nipy/nipype#2209 to fix MRIQC?

**Comment by oesteban** [comment]
No, I have to fix MRIQC first. Let me push some commits.

**Comment by effigies** [comment]
Okay. If it works for you, I'll push a commit here with the latest nipype PR and you can push your MRIQC fixes and pin in one shot.

**Comment by oesteban** [comment]
It works :)

**Comment by oesteban** [comment]
Sorry, I misread the thread. No, nipy/nipype#2209 is not necessary

**Comment by effigies** [comment]
Okay, I collapsed the pin to include all the updates. You can pin MRIQC to dafbfdaac1c4a4765f413812749a93992a1a37d5.

**Comment by oesteban** [comment]
Sweet thanks

**Comment by effigies** [comment]
Updated the fmriprep test in the checklist. If you want to do the same when you push an mriqc branch, I'll merge when they both pass.

**Comment by oesteban** [comment]
Done

**Comment by effigies** [comment]
Not causing a failure but it is a bit unsightly:

```
Error in atexit._run_exitfuncs:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/config.py", line 327, in free_display
    config.stop_display()
AttributeError: 'NipypeConfig' object has no attribute 'stop_display'
```

From: https://circleci.com/api/v1.1/project/github/effigies/fmriprep/861/output/31/0?file=true

I want to go ahead and merge to move forward, if MRIQC passes, but just so you're aware of the issue.

**Comment by oesteban** [comment]
That is because of the absolute import of `nipype` in the atexit function. Not sure if that import could be relative, I guess so.

**Comment by effigies** [comment]
Yup. I'm submitting a patch. Also dropping the verbosity of multi-proc again...

**Pull request merged**
