### PR TITLE
[ENH] Do not save the original name and time stamp of gzip files

### PR DESCRIPTION
**Pull request by oesteban**
Fixes poldracklab/fmriprep#1480

### CODE REVIEW

**Comment by effigies** [comment]
This won't strip the filename from existing gzipped files, which will be copied with nipype's `copyfile`:

https://github.com/poldracklab/niworkflows/blob/2b38c76c48c058ad504bb8ec42322a9d82bb98fe/niworkflows/utils/misc.py#L144

**Comment by oesteban** [comment]
Turns out that the original name of the file is kept after hardlinking. Therefore, if we want this not to happen, we'll need to stop doing so for gzipped files.

**Comment by effigies** [comment]
An alternative is to consider where these files are created.

```Shell
> $ file /oak/stanford/groups/russpold/data/openfmri/derivatives/ds000003/fmriprep_1.2.5/fmriprep/sub-01/*/*.nii.gz | cut -d / -f 11-
fmriprep/sub-01/anat/sub-01_desc-aparcaseg_dseg.nii.gz:                                            gzip compressed data, from Unix
fmriprep/sub-01/anat/sub-01_desc-aseg_dseg.nii.gz:                                                 gzip compressed data, from Unix
fmriprep/sub-01/anat/sub-01_desc-brain_mask.nii.gz:                                                gzip compressed data, was "highres001_N4Corrected0_rbrainmask.nii", last modified: Wed Dec 19 15:12:30 2018, max compression
fmriprep/sub-01/anat/sub-01_desc-preproc_T1w.nii.gz:                                               gzip compressed data, from Unix
fmriprep/sub-01/anat/sub-01_dseg.nii.gz:                                                           gzip compressed data, from Unix
fmriprep/sub-01/anat/sub-01_label-CSF_probseg.nii.gz:                                              gzip compressed data, from Unix
fmriprep/sub-01/anat/sub-01_label-GM_probseg.nii.gz:                                               gzip compressed data, from Unix
fmriprep/sub-01/anat/sub-01_label-WM_probseg.nii.gz:                                               gzip compressed data, from Unix
fmriprep/sub-01/anat/sub-01_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz:                      gzip compressed data, was "highres001_N4Corrected0_rbrainmask_trans.nii", last modified: Wed Dec 19 15:53:07 2018, max compression
fmriprep/sub-01/anat/sub-01_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz:                     gzip compressed data, was "ants_t1_to_mni_Warped.nii", last modified: Wed Dec 19 15:50:08 2018, max compression
fmriprep/sub-01/anat/sub-01_space-MNI152NLin2009cAsym_dseg.nii.gz:                                 gzip compressed data, was "highres001_N4Corrected0_masked_seg_trans.nii", last modified: Wed Dec 19 15:53:11 2018, max compression
fmriprep/sub-01/anat/sub-01_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz:                    gzip compressed data, was "highres001_N4Corrected0_masked_prob_0_trans.nii", last modified: Wed Dec 19 15:50:29 2018, max compression
fmriprep/sub-01/anat/sub-01_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz:                     gzip compressed data, was "highres001_N4Corrected0_masked_prob_1_trans.nii", last modified: Wed Dec 19 15:50:29 2018, max compression
fmriprep/sub-01/anat/sub-01_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz:                     gzip compressed data, was "highres001_N4Corrected0_masked_prob_2_trans.nii", last modified: Wed Dec 19 15:50:35 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-MNI152NLin2009cAsym_boldref.nii.gz:           gzip compressed data, was "ref_image_corrected.nii", last modified: Wed Dec 19 16:00:59 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz:   gzip compressed data, was "ref_image_corrected_brain_mask_maths_trans.nii", last modified: Wed Dec 19 15:55:36 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz: gzip compressed data, was "vol0000_xform-00000_merged.nii", last modified: Wed Dec 19 15:59:02 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-T1w_boldref.nii.gz:                           gzip compressed data, was "ref_image_corrected.nii", last modified: Wed Dec 19 15:56:23 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-T1w_desc-aparcaseg_dseg.nii.gz:               gzip compressed data, was "aparc+aseg_vol_out_trans.nii", last modified: Wed Dec 19 15:52:38 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-T1w_desc-aseg_dseg.nii.gz:                    gzip compressed data, was "aseg_vol_out_trans.nii", last modified: Wed Dec 19 15:52:42 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-T1w_desc-brain_mask.nii.gz:                   gzip compressed data, was "ref_image_corrected_brain_mask_maths_trans.nii", last modified: Wed Dec 19 15:55:23 2018, max compression
fmriprep/sub-01/func/sub-01_task-rhymejudgment_space-T1w_desc-preproc_bold.nii.gz:                 gzip compressed data, was "sub-01_task-rhymejudgment_space-T1w_desc-preproc_bold.nii", last modified: Wed Dec 19 15:55:58 2018, max compression
```

Maybe it makes sense to make sure that the files are cleaned when created as much as possible - if they're created by a non-Python tool, then there's no avoiding a copy - and only do the unzip-rezip filter when we detect that the information is there. I'm not sure if there's an easy way in Python to detect non-zero mtime and non-blank filename.

**Comment by oesteban** [comment]
Okay, as per the IT meeting, let's merge this in and follow up with #296.

**Pull request merged**
