### PR TITLE
[WIP] Fmriprep intergration fixes

### PR DESCRIPTION
**Pull request by rwblair**
Kicking of circle for these changes.

### CODE REVIEW

**Comment by chrisfilo** [comment]
This looks good to me, but what's the relation to #53 ?

**Comment by oesteban** [comment]
#53 is a PR to this one, adding the following:

- This test file -> https://github.com/poldracklab/niworkflows/blob/master/test/common/test_report.py is not currently found by nosetests, so I moved its contents into test_validators. 
- The tests are particularly 2.7 -non compatible. In #53 I am making them compatible.

**Comment by oesteban** [comment]
BTW, the TestHTMLValidator is broken: https://circleci.com/gh/oesteban/niworkflows/25?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by chrisfilo** [comment]
Ok I got it now!

**Comment by shoshber** [comment]
`common/test_reports.py` contained only old versions of tests. I should have gotten rid of it right away, but I saw that circle wasn't running them and pushed it back in priority. Sorry for the confusion.

**Comment by chrisfilo** [comment]
No problem - let's get rid of it then (in a separate PR).

**Comment by oesteban** [comment]
@rwblair please remove this file https://github.com/poldracklab/niworkflows/blob/master/test/common/test_report.py from master in this PR

**Comment by oesteban** [comment]
Thanks! Do you think this is ready to merge? - just modify the issue title if so :)

**Comment by rwblair** [comment]
Aye, doing one last run to make sure it looks good. Will change title to RTM once it finishes.

**Pull request merged**
