### PR TITLE
Update .zenodo.json 

### PR DESCRIPTION
**Pull request by utooley**
Wasn't sure if it was appropriate for me to `[skip ci] ` for a non-code edit.

### CODE REVIEW

**Comment by effigies** [comment]
LGTM. Yeah, there's no good way to validate `.zenodo.json` files (I've looked into it... see https://github.com/bids-standard/pybids/pull/470#issuecomment-520179305), so these are good candidates for `[skip ci]`.

@oesteban I think you set up the Zenodo file for niworkflows. Do we have any preferred ordering? I don't see a `prep_zenodo.py` or anything that will reorder by some criterion.

**Comment by utooley** [comment]
The fMRIPrep ordering says new contributors should go right before Russ (which ends up being before both Chris and then Russ), so I put myself there for fMRIPrep. Should the same apply here? I didn't initially realize that they just showed up in the order they were added in.

**Comment by oesteban** [comment]
We don't have any particular order.

**Comment by effigies** [comment]
With fMRIPrep, we don't really distinguish between authors and contributors, so we treat Russ and Chris as co-last-authors, and then do everybody else by chronological order, just because that's easy.

I don't remember why we split authors and contributors, here. I also suspect it matters even less, because nobody knows what niworkflows is...

Merging.

**Pull request merged**
