### PR TITLE
FIX: BusError in ``DerivativesDataSink``

### PR DESCRIPTION
**Pull request by effigies**
This may not be necessary if we fix compression, but this test I'm starting with should error and be fixed in either case.

Related: https://github.com/poldracklab/fmriprep/issues/1555

### CODE REVIEW

**Comment by effigies** [comment]
BusError successfully reproduced.

**Comment by effigies** [comment]
@oesteban IMO we should just go with this and separately address compression in s/fMRIPrep.

**Comment by oesteban** [comment]
I'm afraid that fMRIPrep didn't like this patch:

```
Node: fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_02_wf.func_derivatives_wf.cifti_bolds
Working directory: /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_02_wf/func_derivatives_wf/cifti_bolds

Node inputs:

base_directory = /out
check_hdr = True
compress = False
desc = 
extra_values = <undefined>
in_file = [['/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_02_wf/gen_cifti/mapflow/_gen_cifti0/vol0000_xform-00000_merged.dtseries.nii']]
keep_dtype = False
meta_dict = <undefined>
source_file = <undefined>
space = 
suffix = ['bold.dtseries']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 381, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1253, in _run_interface
    self.config['execution']['stop_on_first_crash'])))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1175, in _collate_results
    (self.name, '\n'.join(msg)))
Exception: Subnodes of node: cifti_bolds failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 99, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)

  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/bids.py", line 471, in _run_interface
    nii = nb.load(out_file, mmap=False)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/loadsave.py", line 49, in load
    img = image_klass.from_filename(filename, **kwargs)

TypeError: from_filename() got an unexpected keyword argument 'mmap'
```

**Comment by effigies** [comment]
Huh, so CIFTI-2 doesn't support `mmap=False`. That's a nibabel bug, IMO.

**Comment by oesteban** [comment]
I'm inclined to think so. Do you want me to file a bug report?

**Comment by effigies** [comment]
I'm doing it. Also we'll probably need to update `GiftiImage` as well to at least ignore it.

**Comment by oesteban** [comment]
Sounds good! For this interface, would it make sense to roll back and use
mmap=False only when we are certain that the file is to be replaced?

**Comment by effigies** [comment]
I opened a reversion. The other thing we can do is just use `get_data().copy()`.

**Pull request merged**
