### PR TITLE
BET reports

### PR DESCRIPTION
**Pull request by shoshber**
Moving changes that I was making in fmriprep to niworkflows

### CODE REVIEW

**Comment by oesteban** [comment]
Please wait for #22 before merging this. I volunteer to fix the upcoming conflicts.

**Comment by shoshber** [comment]
Oscar--afaik this is complete, so feel free to merge any time

**Comment by oesteban** [comment]
I'll fix the conflicts today so that it this is ready to merge.

We could have a quick meeting on Monday before this and any other merge just to make sure everything is in place and properly done. WDYT @chrisfilo, @shoshber, @rwblair ?

**Comment by chrisfilo** [comment]
Sounds good to me - I'm free all day long.

**Comment by shoshber** [comment]
Mondays are tough for me--pretty much the only times I can meet are 5:30pm or 1:00pm.

You would like to have a meeting before all merges in the future? Did I understand that correctly?

**Comment by chrisfilo** [comment]
I just scheduled a call at 1pm - could we do 12:30 or 1:30?

On Fri, Nov 25, 2016 at 3:23 PM, Shoshana Berleant <notifications@github.com

**Comment by shoshber** [comment]
1:30 pm is ok for me.

**Pull request closed without merging**
