### PR TITLE
RTM/ENH ANTS brain extraction report

### PR DESCRIPTION
**Pull request by shoshber**

### CODE REVIEW

**Comment by chrisfilo** [comment]
FYI: I triggered a rebuild for the 91e99e7 commit. I don't think the `-ti` flag was the problem. Let's see what happens.

**Comment by shoshber** [comment]
If I understand it properly it'll time out again. I think it's because the docker command isn't outputting anything and I added a test to run ANTS which takes longer than 10 minutes. Looking around the internet, `-ti` is for running it interactively, so I thought no harm in trying!

**Comment by shoshber** [comment]
Buuut it's still not outputting anything so it didn't do anything.

**Comment by shoshber** [comment]
I increased the timeout for now (in the interests of time) and made an issue for figuring it out later: https://github.com/poldracklab/niworkflows/issues/55

**Pull request merged**
