### PR TITLE
ENH: ``DerivativesDataSink`` - enable JSON sidecar writing

### LINKED ISSUE #308: Refactor DerivativesDataSink: write metadata sidecars
EDITED: ~~We should extract entities and generate paths with pybids.~~

Using pybids will also simplify that DerivativesDataSink write metadata sidecar JSONs.

Comes from poldracklab/fmriprep#1190, poldracklab/fmriprep#1384, and poldracklab/smriprep#6

### PR DESCRIPTION
**Pull request by oesteban**
This PR makes the input spec of `DerivativesDataSink` dynamic. Those inputs set dynamically are considered metadata entries and stored to a sidecar JSON, if a single output file was sunk. If the output is more than one file metadata is dismissed (we may consider how to tackle multi-outputs in the future).

Close #308, enables poldracklab/fmriprep#1190, poldracklab/fmriprep#1384, poldracklab/smriprep#6

### CODE REVIEW

**Comment by oesteban** [comment]
Maybe worth having an input to tell this interface metadata fields that should be copied from the source file.

**Comment by oesteban** [comment]
Although poldracklab/smriprep#62 failed, the generation of JSON sidecars succeeded. This is ready to merge.

**Comment by effigies** [comment]
Thanks @oesteban. Preparing for a meeting, but this will be top priority this afternoon.

**Comment by oesteban** [comment]
Sure, thanks!

**Comment by oesteban** [comment]
I agree with all said. I'll go ahead and merge since the issue of absolute
paths should be addressed in s/fMRIPrep proper, I believe.

**Pull request merged**
