### PR TITLE
[FIX] Backport gh-443 to 1.0.x series

### PR DESCRIPTION
**Pull request by jdkent**
ref #443 

command used:
```
git cherry-pick 1a8b6959e670e6c5461f752034698ae3cc408a5c^..93649a5c086948d8df596afb94cb4656054cf411
```

### CODE REVIEW

**Comment by effigies** [comment]
This doesn't appear to change the API, so I'm okay with it.

**Comment by jdkent** [comment]
looks like all the relevant tests have passed, should codacy be analyzing the `maint`branches?

**Comment by effigies** [comment]
I don't really care about codacy, TBH. I'll check it occasionally. Anyway, unless there are objections, I think we can go ahead with this...

@oesteban Anything you want to check on before this goes in?

**Comment by oesteban** [comment]
good to go!

**Pull request merged**
