### PR TITLE
TST: Bring EPI brain extraction tests from fMRIPrep

### LINKED ISSUE #371: Move tests of EPI masks from fMRIPrep
Because the code now resides here.

### PR DESCRIPTION
**Pull request by oesteban**
This PR adds a new build job to the CircleCI workflow to tests regressions on the EPI masking workflows migrated from fMRIPrep (#362).

The infrastructure and tests are replicated from fMRIPrep.

The PR makes CircleCI ignore these tests (branches and tags) except for `master` and branches with name `masks?/*` to minimize churn.

Incidentally, minor fixes to #362 are included.

Closes #371

### CODE REVIEW

**Comment by effigies** [comment]
Tests here: https://circleci.com/workflow-run/ee3aab20-9842-4750-af2b-371467207f85

**Comment by oesteban** [comment]
They will eventually show up

**Comment by effigies** [comment]
Oh, there they are. Circle sometimes seems to only make them appear when complete, so I wanted a quick way to click and see, since they're under your user, not the poldracklab user.

**Comment by effigies** [comment]
I think you're missing a `niworkflows/func/tests/__init__.py`.

**Comment by oesteban** [comment]
@effigies thumbs-up?

**Comment by oesteban** [comment]
Since this is not fMRIPrep proper, I'll go take the leap. Hopefully not waiting on your review does not backfire.

**Pull request merged**
