### PR TITLE
ENH/TEST: Add all valid entities to fmriprep report specification

### LINKED ISSUE #446: include the other possible entities for ordering the reportlets
[fmriprep.yml](https://github.com/poldracklab/niworkflows/blob/4e9181fd31f3a1b216b5edcf040bd5533c400e9d/niworkflows/reports/fmriprep.yml#L36) should include [all the valid entities](https://bids-specification.readthedocs.io/en/stable/99-appendices/04-entity-table.html) for ordering the reportlets. With #443 merged, including the other entities should not impact any files that do not include those entities.

I believe the ordering should be:
```
session,task,acquisition,ceagent,reconstruction,direction,run,echo(?)
```

for example, the current yml file will not generate reports for both:
```
sub-01_task-rest_acq-mb_bold.nii.gz
sub-01_task-rest_acq-sb_bold.nii.gz
```

### PR DESCRIPTION
**Pull request by jdkent**
fixes #446

### CODE REVIEW

**Comment by effigies** [comment]
This looks reasonable to me. Guess I should have held off on 1.0.4. Do we want this in a bug-fix release of fMRIPrep? If so, can you target `maint/1.0.x`?

**Comment by jdkent** [comment]
I should have realized this is also a change I wanted to make to get all the reports out as expected, but does fmriprep use [reports-spec.yml](https://github.com/poldracklab/fmriprep/blob/63a661b20ec68e1aa08949d5dd6fd17381ea1d52/fmriprep/data/reports-spec.yml) as its reports specification?

**Comment by effigies** [comment]
Ah, no. It looks like fMRIPrep has its own: https://github.com/poldracklab/fmriprep/blob/master/fmriprep/data/reports-spec.yml#L30

Should we just apply this change over there?

**Comment by jdkent** [comment]
I believe that would be the solution to get the behavior I wanted. Is `fmriprep.yml` in niworkflows just for testing purposes?

**Comment by effigies** [comment]
IDK. You'll have to ask @oesteban.

**Comment by effigies** [comment]
Anyway, would you like to open that PR, or should I? You can do it off the `maint/1.5.x` branch, and it will get merged into `master` afterwards.

**Comment by jdkent** [comment]
once poldracklab/fmriprep#1937 is merged, I can open the followup pull request to change reports-spec against the `maint/1.5.x` branch

**Comment by effigies** [comment]
Oh. Want to just add that change to poldracklab/fmriprep#1937? Or keep it separate? I'm good to merge that one (I kind of thought I already had...), so either way.

**Comment by jdkent** [comment]
I'll add it to that pull request (for simplicity)

**Pull request merged**
